name: ci_cd

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  testing:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust toolchain
        run: rustup component add clippy rust-std-x86_64-unknown-linux-gnu
      - name: Clippy check
        run: cargo clippy --all-targets --all-features -- -D warnings -W clippy::style -D clippy::perf